apiVersion: v1
kind: Service
metadata:
  name: novapay-payment-canary
  namespace: default

spec:
  selector:
    app: novapay-payment-api-canary

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: ClusterIP